name: generate-pb
on: [push]
jobs:
  generate-cpp-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install libraries
        run: |
          sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler
      - name: generate
        run:  protoc -I=. --cpp_out=. aisaaccommand.proto
        working-directory: ./protos
      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-public
          path: ./protos/
