name: generate-pb
on: [push]
jobs:
  job_1:
    name: generate-cpp-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install libraries
        run: |
          sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler
      - name: generate
        run:  protoc -I=. --cpp_out=. aisaaccommand.proto
        working-directory: ./protos
      - name: save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-public
          path: ./protos/
   job_2:
     name: generate-nanopb-files
     needs: job_1
     runs-on: ubuntu-lates
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
       - name: install libraries
         run: |
           python -m pip install protobuf grpcio-tools
       - name: Clone nanopb
         run: |
           git clone https://github.com/nanopb/nanopb.git
       - name: generate
         run: |
           python ../nanopb/generator/nanopb_generator.py aisaaccommand.proto
         working-directory: ./protos
       - name: save artifacts
         uses: actions/upload-artifact@v3
         with:
           name: nanopb-files
           path: ./protos/
